# Generated by Django 5.0.7 on 2024-07-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityStatistics',
            new_name='CitiesStatistics',
        ),
        migrations.AlterModelTable(
            name='citiesstatistics',
            table='cities_statistics',
        ),
    ]
